import { useState } from 'react'
import axios from 'axios'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'

export default function InstagramPostCreator() {
  const [caption, setCaption] = useState('')
  const [imageUrl, setImageUrl] = useState('')
  const [accessToken, setAccessToken] = useState('')  // This will be populated after the user logs in and links Instagram
  const [loading, setLoading] = useState(false)

  const handlePostToInstagram = async () => {
    setLoading(true)
    try {
      const response = await axios.post('http://localhost:5000/api/instagram/post', {
        access_token: accessToken,
        image_url: imageUrl,
        caption,
      })

      if (response.data.success) {
        alert('Post successfully shared to Instagram!')
      }
    } catch (error) {
      console.error('Error posting to Instagram:', error)
      alert('Failed to post to Instagram')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="space-y-4">
      <h2 className="text-lg font-bold">Instagram Post Creation</h2>

      <Textarea
        placeholder="Write a caption for your Instagram post"
        value={caption}
        onChange={(e) => setCaption(e.target.value)}
      />
      
      <Input
        placeholder="Image URL (generated by AI)"
        value={imageUrl}
        onChange={(e) => setImageUrl(e.target.value)}
      />
      
      <Button onClick={handlePostToInstagram} disabled={loading}>
        {loading ? 'Posting...' : 'Post to Instagram'}
      </Button>
    </div>
  )
}
